### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VipIPru** [Abestanis/APython_PyToApk#1]
How does it work?

**Comment by Abestanis** [comment]
Hi, this is a tool that packages your Python code into an apk (Android App), which can then be installed on your phone.
You need to run the `build.py` script and give it the path to the directory containing your Python files that should be in the app.

You need at least a `main.py` file in the directory, that file will be run when the app starts.
There is also an [example directory here](https://github.com/Abestanis/APython_PyToApk/tree/main/examplePythonProgram), which you can use to test this.

There is also an explanation of what to do in the [Readme](https://github.com/Abestanis/APython_PyToApk#the-pytoapk-tool) with further details. Also, make sure you have all the requirements (mentioned in the Readme) installed, like the Android SDK.

To execute the app, you also need [APython host app](https://github.com/Abestanis/APython) installed on your phone. This app allows you to install Python versions on your phone, and you need to install at least one Python version before you can run the generated app with your Python code.

It's just like installing Python on Windows or Linux, before you can run any `.py` files.


It has been a while since I actively worked on this, if you need further help or encounter any problems, don't hesitate to ask.

**Comment by VipIPru** [comment]
Thank you very much
